AWSTemplateFormatVersion: "2010-09-09"
Description: "An example template with an IAM role for a Lambda state machine."
Resources:
  StatesExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - !Sub states.${AWS::Region}.amazonaws.com
            Action: "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: StatesExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "cloudwatch:PutMetricData"
                Resource: "*"

  MyStateMachine:
    Type: "AWS::StepFunctions::StateMachine"
    Properties:
      DefinitionString:
        |-
          {
            "Comment": "A Hello World example demonstrating various state types of the Amazon States Language. It is composed of flow control states only, so it does not need resources to run.",
            "StartAt": "Pass",
            "States": {
              "Pass": {
                "Comment": "A Pass state passes its input to its output, without performing work. They can also generate static JSON output, or transform JSON input using filters and pass the transformed data to the next state. Pass states are useful when constructing and debugging state machines.",
                "Type": "Pass",
                "Result": {
                  "IsHelloWorldExample": true
                },
                "Next": "Hello World example?"
              },
              "Hello World example?": {
                "Comment": "A Choice state adds branching logic to a state machine. Choice rules can implement many different comparison operators, and rules can be combined using And, Or, and Not",
                "Type": "Choice",
                "Choices": [
                  {
                    "Variable": "$.IsHelloWorldExample",
                    "BooleanEquals": true,
                    "Next": "Yes"
                  },
                  {
                    "Variable": "$.IsHelloWorldExample",
                    "BooleanEquals": false,
                    "Next": "No"
                  }
                ],
                "Default": "Yes"
              },
              "Yes": {
                "Type": "Pass",
                "Next": "Wait 3 sec"
              },
              "No": {
                "Type": "Fail",
                "Cause": "Not Hello World"
              },
              "Wait 3 sec": {
                "Comment": "A Wait state delays the state machine from continuing for a specified time.",
                "Type": "Wait",
                "Seconds": 3,
                "Next": "Parallel State"
              },
              "Parallel State": {
                "Comment": "A Parallel state can be used to create parallel branches of execution in your state machine.",
                "Type": "Parallel",
                "Next": "Hello World",
                "Branches": [
                  {
                    "StartAt": "Hello",
                    "States": {
                      "Hello": {
                        "Type": "Pass",
                        "Next": "PutMetricData"
                      },
                      "PutMetricData": {
                        "Type": "Task",
                        "Parameters": {
                          "MetricData": [
                            {
                              "MetricName": "Hello",
                              "Value": 1,
                              "Unit": "Count"
                            }
                          ],
                          "Namespace": "FlowMonitor"
                        },
                        "Resource": "arn:aws:states:::aws-sdk:cloudwatch:putMetricData",
                        "End": true
                      }
                    }
                  },
                  {
                    "StartAt": "World",
                    "States": {
                      "World": {
                        "Type": "Pass",
                        "Next": "PutMetricData (1)"
                      },
                      "PutMetricData (1)": {
                        "Type": "Task",
                        "Parameters": {
                          "MetricData": [
                            {
                              "MetricName": "World",
                              "Value": 1,
                              "Unit": "Count"
                            }
                          ],
                          "Namespace": "FlowMonitor"
                        },
                        "Resource": "arn:aws:states:::aws-sdk:cloudwatch:putMetricData",
                        "End": true
                      }
                    }
                  }
                ]
              },
              "Hello World": {
                "Type": "Pass",
                "End": true
              }
            }
          }
      RoleArn: !GetAtt [ StatesExecutionRole, Arn ]